### ISSUE TITLE
Linux arm64 pre-built binaries in release

### ISSUE THREAD

**Issue by czyt** [nwtgck/piping-server-rust#199]
could u build arm version in release?thank u.

**Comment by nwtgck** [comment]
I'd like to do and I'm finding the way to do so.

As another choice, we can use arm builds in <https://github.com/nwtgck/piping-server-pkg/releases>.

**Comment by nwtgck** [comment]
ARM for Linux and ARM for macOS is now provided!

https://github.com/nwtgck/piping-server-rust/releases/tag/v0.10.2
