### ISSUE TITLE
Termux build errors 

### ISSUE THREAD

**Issue by gyurmogyuri** [nwtgck/piping-server-rust#98]
`addeq r12,r11,#(GFp_poly1305_emit-.Lpoly1305_init)      ^                                                      /data/data/com.termux/files/home/.cargo/registry/src/github.com-1285ae84e5963aae/ring-0.16.15/pregenerated/poly1305-armv4-linux32.S:185:2: error: out of range immediate fixup value                                             addne r12,r11,#(poly1305_emit_neon-.Lpoly1305_init)     ^                                                      /data/data/com.termux/files/home/.cargo/registry/src/github.com-1285ae84e5963aae/ring-0.16.15/pregenerated/poly1305-armv4-linux32.S:187:2: error: out of range immediate fixup value                                             addne r11,r11,#(poly1305_blocks_neon-.Lpoly1305_init)   ^                                                      thread 'main' panicked at 'execution failed', /data/data/com.termux/files/home/.cargo/registry/src/github.com-1285ae84e5963aae/ring-0.16.15/build.rs:664:9              note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace                                 warning: build failed, waiting for other jobs to finish...                                                      error: build failed`

**Comment by nwtgck** [comment]
@gyurmogyuri Could you tell your environment?

**Comment by nwtgck** [comment]
When you answer the question I will open this.
